export const PRODUCT_GET_LIST_ERR = 'PRODUCT_GET_LIST_ERR';
export const PRODUCT_GET_LIST_REQ = 'PRODUCT_GET_LIST_REQ';
export const PRODUCT_GET_LIST_RES = 'PRODUCT_GET_LIST_RES';

export const PRODUCT_GET_DETAIL_ERR = 'PRODUCT_GET_DETAIL_ERR';
export const PRODUCT_GET_DETAIL_REQ = 'PRODUCT_GET_DETAIL_REQ';
export const PRODUCT_GET_DETAIL_RES = 'PRODUCT_GET_DETAIL_RES';
